In [27]:
# Ex 1 Day 3
import numpy as np

a = np.zeros(10)
a[4] = 1
print(a)
print()

b = np.arange(10,50)
print(b)
print()

c = b[::-1]
print(c)
print()

d = np.arange(0,9).reshape(3,3)
print(d)
print()

e = np.array([1,2,0,0,4,0])
e = np.where(e!=0)
print(e)
print()

f = np.mean(np.random.rand(30))
print(f)
print()

g = np.ones((3,3))
g[1,1] = 0
print(g)
print()

h1 = np.zeros(8)
h1[::2] = 1
h2 = h1[::-1]
h = np.array([h1,h2,h1,h2,h1,h2,h1,h2])
print(h)
print()

i = np.array([[1,0],[0,1]])
i = np.tile(i,(4,4))
print(i)
print()

j = np.arange(11)
idxj = np.where((j<=8)&(j>=3))
j[idxj] *= -1
print(j)
print()

k = np.random.random(10)
k[:] = np.sort(k)
print(k)
print()

lA = np.random.randint(0,2,5)
lB = np.random.randint(0,2,5)
equal = all(lA == lB)
print(equal)
print()

m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = m.astype(float)
print(m.dtype)
print()

A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
print(C)
D = np.diagonal(C)
print(D)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(array([0, 1, 4], dtype=int64),)

0.5439023067636731

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]

[0.04015325 0.04533281 0.16598302 0.27342017 0.31570476 0.38286416
 0.42540193 0.42560085 0.67095291 0.78505753]

False

int32
float64

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66

In [4]:
# Ex 2 Day 3
# Program to multiply two matrices using nested loops
import numpy as np
import random

N = 250

# NxN matrix
X = np.random.randint(100, size=(N,N))

# Nx(N+1) matrix
Y = np.random.randint(100, size=(N,N+1))

# new method
result = np.matmul(X,Y)

# old method
resultold = []
for i in range(N):
    resultold.append([0] * (N+1))

# iterate through rows of X
for i in range(len(X)):
    # iterate through columns of Y
    for j in range(len(Y[0])):
        # iterate through rows of Y
        for k in range(len(Y)):
            resultold[i][j] += X[i][k] * Y[k][j]

# checking if same
print(np.where(result != resultold))

(array([], dtype=int64), array([], dtype=int64))


In [ ]:
# Ex 3 Day 3
class Person(object):
    def __init__(self, name, surname):
        self.name = name
        self.surname = surname
    def __str__(self):
        return "%s %s" % (self.name,self.surname)

class Student(Person):
    def __init__(self, name, surname, subject):
        Person.__init__(self, name, surname)
        self.subject = subject
    def __str__(self):
        return "%s %s, %s" % (self.name,self.surname,self.subject)

me = Person('Edvin','Andersson')
print(me)
measastudent = Student('Edvin','Andersson','Chemistry')
print(measastudent)